name: CI

on:
  push:
    branches: [ "main" ]
env:
  CONTAINER_NAME: "container-security-scan-action"
  RELEASE: "latest"
permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ${{ env.CONTAINER_NAME }}:${{ env.RELEASE }} .
    - name: Tag the Docker Image
      run: docker tag ${{ env.CONTAINER_NAME }}:${{ env.RELEASE }} ghcr.io/trendmicro/${{ env.CONTAINER_NAME }}:${{ env.RELEASE }}
    - name: Login to GH Packages
      run: docker login ghcr.io -u trendmicro --password ${{ secrets.GITHUB_TOKEN }}
    - name: Push to Packages
      run: docker push ghcr.io/trendmicro/${{ env.CONTAINER_NAME }}:${{ env.RELEASE }}
    